### PR TITLE
Added specs

### PR DESCRIPTION
**Pull request by vramana**
- [x] find-next
- [x] find-previous
- [x] find-next-case-sensitive
- [x] find-previous-case-sensitive

### CODE REVIEW

**Comment by vramana** [comment]
@mark-hahn I have written basic unit tests. Can you review this PR?

**Comment by mark-hahn** [comment]
That looks awesome.  I'll try it out tomorrow.

**Comment by mark-hahn** [comment]
Released in 0.15.0

Thanks again!

**Comment by mark-hahn** [comment]
I just noticed the readme still says to add specs.  You forgot that mod.  :-)

I'll change it next release.

**Comment by vramana** [comment]
Oops!! Anyway, it was my pleasure to contribute and a good learning exercise for me.

**Pull request merged**
