### PR TITLE
Fix #11 Find-previous goes forward when no selection 

### LINKED ISSUE #11: find-previous goes forward when no selection
find-previous goes forward when no selection.  This has probably been broken for a long time.

### PR DESCRIPTION
**Pull request by kumarrishav**

### CODE REVIEW

**Comment by mark-hahn** [comment]
Bug: The find-forward now goes two selections forward instead of one when nothing was selected.  

I guess you have to start a new PR for this since I merged this PR.  Github has a problem that I can't test a PR without merging it first.

**Comment by kumarrishav** [comment]
@mark-hahn You can test the PR without merging. just download the patch (u can do this by adding .patch in pull request link) and apply the patch in a branch locally (create a branch for testing). Then test it

**Comment by mark-hahn** [comment]
Thanks.  I will do that.

**Comment by mark-hahn** [comment]
> u can do this by adding .patch in pull request link

I don't understand this.  I have only seen pull requests at github.  What is a "pull request link" and where do I run the command to add `.patch`?

**Comment by mark-hahn** [comment]
I figured out that the "link" is https://github.com/mark-hahn/find-selection/pull/14.patch.  How do I do a pull from that link?  I always use sourcetree but I assume I am suppose to use the git command line.  What is the git command?

**Comment by mark-hahn** [comment]
I tried this ...

```
C:\atom\find-selection>git pull https://github.com/mark-hahn/find-selection/pull/14.patch
remote: Please upgrade your git client.
remote: GitHub.com no longer supports git over dumb-http: https://github.com/blog/809-git-dumb-http-transport-to-be-turned-off-in-90-days
fatal: unable to access 'https://github.com/mark-hahn/find-selection/pull/14.patch/': The requested URL returned error: 403
```

**Comment by kumarrishav** [comment]
Yeah..you are right.  https://github.com/mark-hahn/find-selection/pull/14.patch  (adding .patch give the patch). now ctrl+s (save it in your some folder). 
Now go to your master branch, create a new branch and checkout to it.  then
git apply link_to_the_patch
now reload the atom, and test the patch

**Comment by kumarrishav** [comment]
Just go to this link (click on this link and save it)

**Comment by kumarrishav** [comment]
Better to open it in new tab and then ctrl+s

**Comment by mark-hahn** [comment]
OK, I figured it out.  Worked great.  I'm learning more from you than you from me.

fixed in 0.13.8

**Comment by mark-hahn** [comment]
I just realized that when I use this method you don't get credit for the PR.  Is this correct?

**Comment by kumarrishav** [comment]
Yeah, because you merged this as your branch (which u develop for testing, i guess). you can use this for testing of PR. If PR is okay, then you can merge my pull request. Credit is given only when my code(pull request) is merged in master branch.  Anyway it's okay :) It's all about learning.

**Comment by mark-hahn** [comment]
Ah, I get it.  I will only use it for testing in the future.

**Pull request merged**
