### PR TITLE
Fix #15 Case sensitive search

### LINKED ISSUE #15: Support case-sensitive searches
@mark-hahn What key-binding you suggest for this.?

### PR DESCRIPTION
**Pull request by kumarrishav**
Issue 15 fix

### CODE REVIEW

**Comment by kumarrishav** [comment]
@mark-hahn hope it's fine :)

**Comment by kumarrishav** [comment]
I think after this patch, CHANGELOG.md and README.md should be updated as new key-binding has introduced.

**Comment by mark-hahn** [comment]
Works great.

**Comment by mark-hahn** [comment]
I always update changelog -- you can update readme whenever you want (grin).

**Comment by kumarrishav** [comment]
Sure :) Creating new issue for updating README.md in #17

**Pull request merged**
